openapi: 3.0.0
info:
  title: Project API
  version: 0.1.0
  description: API specification for the project.

paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
